### ISSUE TITLE
Crashing when tapping on the location button on a widget

### ISSUE THREAD

**Issue by tgp1994** [thuryn/your-local-weather#156]
I'm getting AppCrashes when I tap on the location button on a widget. I think the location may be invalid since the widget is blank.

(Attached: log)
[log-yourlocalweather.txt](https://github.com/thuryn/your-local-weather/files/4619754/log-yourlocalweather.txt)

**Comment by iillyyaa2033** [comment]
@tgp1994, 
1. Can this issue still be reproduced?
2. Are you familiar with logcat?

**Comment by tgp1994** [comment]
1. I had reset the app data awhile ago to get it working again, but I was able to reproduce the issue just now. These were my steps:
- Make sure the widget is set to a static, valid location (location #1 since we can only have one manual location at this time)
- Go into the app, edit the locations list, and remove the static location
- Go back to the widget, and try tapping the location button. I had to tap it a few times before my phone tells me the app is crashing.

2. Please find a logcat log attached. :) It's filtered to the app name, hopefully that doesn't exclude anything you might be looking for?

[Log-2020-08-10-03.35.33.zip](https://github.com/thuryn/your-local-weather/files/5053776/Log-2020-08-10-03.35.33.zip)

**Comment by iillyyaa2033** [comment]
Thanks for explanation, now I can reproduce this issue too.

The error is
```
08-11 01:59:24.550 E/AndroidRuntime(4338): FATAL EXCEPTION: main
08-11 01:59:24.550 E/AndroidRuntime(4338): Process: org.thosp.yourlocalweather, PID: 4338
08-11 01:59:24.550 E/AndroidRuntime(4338): java.lang.RuntimeException: Unable to start receiver org.thosp.yourlocalweather.widget.ExtLocationWithForecastWidgetProvider: java.lang.NullPointerException: Attempt to invoke virtual method 'long java.lang.Long.longValue()' on a null object reference
08-11 01:59:24.550 E/AndroidRuntime(4338): 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3087)
08-11 01:59:24.550 E/AndroidRuntime(4338): 	at android.app.ActivityThread.-wrap18(ActivityThread.java)
08-11 01:59:24.550 E/AndroidRuntime(4338): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1591)
08-11 01:59:24.550 E/AndroidRuntime(4338): 	at android.os.Handler.dispatchMessage(Handler.java:102)
08-11 01:59:24.550 E/AndroidRuntime(4338): 	at android.os.Looper.loop(Looper.java:154)
08-11 01:59:24.550 E/AndroidRuntime(4338): 	at android.app.ActivityThread.main(ActivityThread.java:6236)
08-11 01:59:24.550 E/AndroidRuntime(4338): 	at java.lang.reflect.Method.invoke(Native Method)
08-11 01:59:24.550 E/AndroidRuntime(4338): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
08-11 01:59:24.550 E/AndroidRuntime(4338): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
08-11 01:59:24.550 E/AndroidRuntime(4338): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'long java.lang.Long.longValue()' on a null object reference
08-11 01:59:24.550 E/AndroidRuntime(4338): 	at org.thosp.yourlocalweather.utils.AppPreference.setCurrentLocationId(AppPreference.java:546)
08-11 01:59:24.550 E/AndroidRuntime(4338): 	at org.thosp.yourlocalweather.widget.AbstractWidgetProvider.performActionOnReceiveForWidget(AbstractWidgetProvider.java:171)
08-11 01:59:24.550 E/AndroidRuntime(4338): 	at org.thosp.yourlocalweather.widget.AbstractWidgetProvider.onReceive(AbstractWidgetProvider.java:127)
08-11 01:59:24.550 E/AndroidRuntime(4338): 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3080)
08-11 01:59:24.550 E/AndroidRuntime(4338): 	... 8 more
```

**Comment by iillyyaa2033** [comment]
@tgp1994 cannot reproduce this bug on 622843a8. Maybe you can?

**Comment by tgp1994** [comment]
I'm seeing a lot of translation commits since the last release which I'm using, but I could give it a go if there's a test build available?

**Comment by iillyyaa2033** [comment]
Here you are:
[YourLocationWeather-release.zip](https://github.com/thuryn/your-local-weather/files/5070682/YourLocationWeather-release.zip)

Keep in mind that this APK signed different key when in 'releases' section, so Android might refuse to install this version. In this case you have to delete application and this APK.

**Comment by tgp1994** [comment]
Thank you for posting that! I removed the old app and replaced it with that one. When I try to place any widget though, it says there was an error loading the widget. I haven't seen that before.

![Screenshot_20200813-112448](https://user-images.githubusercontent.com/842942/90172826-6899ec80-dd58-11ea-8269-59841c60576a.jpg)

**Comment by thuryn** [comment]
Could you, please, try to reproduce the issue on the version 5.6.1 (it's going to be released in hours.

**Comment by tgp1994** [comment]
I'm sorry, but I don't currently have the ability to compile from source at this time. I'll need to wait for the release unless a compiled apk can be provided.

**Comment by inson1** [comment]
@gbakeman What about now?

**Comment by gbakeman** [comment]
Hi @inson1 , I'm sorry but I've moved on to https://github.com/breezy-weather/breezy-weather. I have to wonder if this was fixed since no one else has commented since?
