### ISSUE TITLE
Frequent crashing without location enabled

### ISSUE THREAD

**Issue by TheShanMan** [thuryn/your-local-weather#184]
This app crashes quite frequently for me and I finally figured out why after installing the Scoop app to capture the exception details. I don't enable location for this app and instead enter my location manually. That seems to be why. Here's the exception. I look forward to these crashes going away hopefully if you're willing to fix it!

`FATAL EXCEPTION: main
Process: org.thosp.yourlocalweather, PID: 27522
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean org.thosp.yourlocalweather.model.Location.isEnabled()' on a null object reference
	at org.thosp.yourlocalweather.service.StartAutoLocationJob.getLocationForNotification(StartAutoLocationJob.java:195)
	at org.thosp.yourlocalweather.service.StartAutoLocationJob.checkNotificationAndReturnLocationForNotification(StartAutoLocationJob.java:182)
	at org.thosp.yourlocalweather.service.StartAutoLocationJob.access$100(StartAutoLocationJob.java:24)
	at org.thosp.yourlocalweather.service.StartAutoLocationJob$1.onServiceConnected(StartAutoLocationJob.java:240)
	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:2077)
	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:2110)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7870)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)`

**Comment by thuryn** [comment]
Hopefully fixed in v5.7.7

**Comment by TheShanMan** [comment]
Yes. Thank you!!!
