### ISSUE TITLE
Frequent crashes

### ISSUE THREAD

**Issue by TheShanMan** [thuryn/your-local-weather#188]
With the recent update (5.8.7) I get crashes so frequently that I effectively can't navigate in the app, nor can I get weather updates in a widget or the notification. I get crashes like these 2...

`FATAL EXCEPTION: main
Process: org.thosp.yourlocalweather, PID: 13734
java.lang.SecurityException: Not allowed to delete channel yourLocalWeather with a foreground service
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2426)
	at android.os.Parcel.createException(Parcel.java:2410)
	at android.os.Parcel.readException(Parcel.java:2393)
	at android.os.Parcel.readException(Parcel.java:2335)
	at android.app.INotificationManager$Stub$Proxy.deleteNotificationChannel(INotificationManager.java:4446)
	at android.app.NotificationManager.deleteNotificationChannel(NotificationManager.java:1002)
	at org.thosp.yourlocalweather.utils.NotificationUtils.checkAndCreateNotificationChannel(NotificationUtils.java:90)
	at org.thosp.yourlocalweather.utils.NotificationUtils.getNotification(NotificationUtils.java:116)
	at org.thosp.yourlocalweather.utils.NotificationUtils.getWeatherNotification(NotificationUtils.java:66)
	at org.thosp.yourlocalweather.utils.NotificationUtils.weatherNotification(NotificationUtils.java:40)
	at org.thosp.yourlocalweather.settings.fragments.NotificationPreferenceFragment.entrySummary(NotificationPreferenceFragment.java:133)
	at org.thosp.yourlocalweather.settings.fragments.NotificationPreferenceFragment.updateSummary(NotificationPreferenceFragment.java:150)
	at org.thosp.yourlocalweather.settings.fragments.NotificationPreferenceFragment.updateSummaries(NotificationPreferenceFragment.java:188)
	at org.thosp.yourlocalweather.settings.fragments.NotificationPreferenceFragment.onResume(NotificationPreferenceFragment.java:176)
	at android.app.Fragment.performResume(Fragment.java:2551)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1346)
	at android.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1581)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1642)
	at android.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2220)
	at android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2166)
	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2067)
	at android.app.FragmentManagerImpl$1.run(FragmentManager.java:742)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7870)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.notification.NotificationManagerService$11.enforceDeletingChannelHasNoFgService(NotificationManagerService.java:3791)
	at com.android.server.notification.NotificationManagerService$11.deleteNotificationChannel(NotificationManagerService.java:3804)
	at android.app.INotificationManager$Stub.onTransact(INotificationManager.java:1861)
	at android.os.Binder.execTransactInternal(Binder.java:1179)
	at android.os.Binder.execTransact(Binder.java:1143)
`

And

`FATAL EXCEPTION: main
Process: org.thosp.yourlocalweather, PID: 28616
java.lang.RuntimeException: Unable to start service org.thosp.yourlocalweather.service.UpdateWeatherService@a67c6bc with null: java.lang.SecurityException: Not allowed to delete channel yourLocalWeather with a foreground service
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4724)
	at android.app.ActivityThread.access$2000(ActivityThread.java:256)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2129)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7870)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
Caused by: java.lang.SecurityException: Not allowed to delete channel yourLocalWeather with a foreground service
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2426)
	at android.os.Parcel.createException(Parcel.java:2410)
	at android.os.Parcel.readException(Parcel.java:2393)
	at android.os.Parcel.readException(Parcel.java:2335)
	at android.app.INotificationManager$Stub$Proxy.deleteNotificationChannel(INotificationManager.java:4446)
	at android.app.NotificationManager.deleteNotificationChannel(NotificationManager.java:1002)
	at org.thosp.yourlocalweather.utils.NotificationUtils.checkAndCreateNotificationChannel(NotificationUtils.java:90)
	at org.thosp.yourlocalweather.utils.NotificationUtils.getNotificationForActivity(NotificationUtils.java:70)
	at org.thosp.yourlocalweather.service.UpdateWeatherService.onStartCommand(UpdateWeatherService.java:134)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4706)
	... 9 more
`

**Comment by TheShanMan** [comment]
My wife was still on 5.8.0 so I used titanium backup to get that version onto my phone and I can stick with that until this bug is fixed.

**Comment by TheShanMan** [comment]
@thuryn have you seen this yet? Several releases have gone by and they all still have this problem. I have to keep going back to 5.8.0. Newer versions are completely broken for me.

**Comment by thuryn** [comment]
Sorry, I haven't seen it yet nor did know about the issue. I'll check it. What version of Android do you have?

**Comment by TheShanMan** [comment]
Awesome, thanks! I'm on android 12.

**Comment by thuryn** [comment]
Could you, please, check this version: https://mega.nz/file/mlEVyYQZ#Rmr8DhbcKxvUqEZutGCnPSTvdaVGvo0xDuj-9_uWCK8 
I'm curious if it works fine and the notification works also.

**Comment by thuryn** [comment]
fixed in v5.8.15

**Comment by TheShanMan** [comment]
Thank you @thuryn ! Sorry for being slow - I did try your debug version and it's been working. Looking forward to getting .15 installed.
